name: Publish Workflow / Bump version
description: It bump version of provided package

inputs:
  package_name:
    description: Package's name
    required: true
  version_type:
    description: <custom> | major | minor | patch | premajor | preminor | prepatch | prerelease
    required: true
  prerelease_id:
    description: Prerelease identifier
    required: false

outputs:
  prev_version:
    value: ${{ steps.internal_id_prev_version.outputs.value }}
  next_version:
    value: ${{ steps.internal_id_next_version.outputs.value }}
  is_stable_release:
    value: ${{ steps.internal_id_is_stable_release.outputs.value }}

runs:
  using: composite
  steps:
    - name: Saving current version to env
      id: internal_id_prev_version
      run: echo "value=$(yarn workspace ${{ inputs.package_name }} node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Bump ${{ inputs.package_name }} package by version type
      if: ${{ !inputs.prerelease_id }}
      run: yarn workspace ${{ inputs.package_name }} run g:npm:version ${{ inputs.version_type }}
      shell: bash

    - name: Bump ${{ inputs.package_name }} package by version type (with --preid flag)
      if: ${{ inputs.prerelease_id }}
      run: yarn workspace ${{ inputs.package_name }} run g:npm:version ${{ inputs.version_type }} --preid ${{ inputs.prerelease_id }}
      shell: bash

    - name: Saving new version to env
      id: internal_id_next_version
      run: echo "value=$(yarn workspace ${{ inputs.package_name }} node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Detect release type
      id: internal_id_is_stable_release
      run: |
        if yarn run semver ${{ steps.internal_id_next_version.outputs.value }} --range '>=0.0.0'; then
          echo "value=true" >> $GITHUB_OUTPUT
        else
          echo "value=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
