import type { MetaRecord } from 'nextra';

const meta: MetaRecord = {
  '##': {
    type: 'separator',
    title: 'Раскладка',
  },
  'box': 'Box',
  'button-group': 'ButtonGroup',
  'card-grid': 'CardGrid',
  'card-scroll': 'CardScroll',
  'cell-button-group': 'CellButtonGroup',
  'div': 'Div',
  'fixed-layout': 'FixedLayout',
  'flex': 'Flex',
  'form-layout-group': 'FormLayoutGroup',
  'group': 'Group',
  'radio-group': 'RadioGroup',
  'separator': 'Separator',
  'simple-grid': 'SimpleGrid',
  'spacing': 'Spacing',
  'split-layout': 'SplitLayout',
  '#####': {
    type: 'separator',
    title: 'Формы и поля ввода',
  },
  'checkbox': 'Checkbox',
  'chips-input': 'ChipsInput',
  'chips-select': 'ChipsSelect',
  'custom-select': 'CustomSelect',
  'drop-zone': 'DropZone',
  'file': 'File',
  'form-field': 'FormField',
  'form-item': 'FormItem',
  'form-status': 'FormStatus',
  'input': 'Input',
  'native-select': 'NativeSelect',
  'radio': 'Radio',
  'segmented-control': 'SegmentedControl',
  'select': 'Select',
  'select-mimicry': 'SelectMimicry',
  'slider': 'Slider',
  'switch': 'Switch',
  'textarea': 'Textarea',
  'write-bar': 'WriteBar',
  '######': {
    type: 'separator',
    title: 'Работа с датами',
  },
  'calendar': 'Calendar',
  'calendar-range': 'CalendarRange',
  'date-input': 'DateInput',
  'date-range-input': 'DateRangeInput',
  '#######': {
    type: 'separator',
    title: 'Кнопки',
  },
  'button': 'Button',
  'cell': 'Cell',
  'cell-button': 'CellButton',
  'icon-button': 'IconButton',
  'simple-cell': 'SimpleCell',
  'tool-button': 'ToolButton',
  '####': {
    type: 'separator',
    title: 'Навигация',
  },
  'epic': 'Epic',
  'pagination': 'Pagination',
  'panel': 'Panel',
  'panel-header': 'PanelHeader',
  'panel-header-context': 'PanelHeaderContext',
  'root': 'Root',
  'subnavigation-bar': 'SubnavigationBar',
  'tabs': 'Tabs',
  'view': 'View',
  '###': {
    type: 'separator',
    title: 'Обратная связь',
  },
  'alert': 'Alert',
  'progress': 'Progress',
  'pull-to-refresh': 'PullToRefresh',
  'screen-spinner': 'ScreenSpinner',
  'skeleton': 'Skeleton',
  'snackbar': 'Snackbar',
  'spinner': 'Spinner',
  '##########': {
    type: 'separator',
    title: 'Модальные окна',
  },
  'action-sheet': 'ActionSheet',
  'modal-card': 'ModalCard',
  'modal-card-base': 'ModalCardBase',
  'modal-dismiss-button': 'ModalDismissButton',
  'modal-outside-button': 'ModalOutsideButton',
  'modal-page': 'ModalPage',
  'modal-page-header': 'ModalPageHeader',
  'popover': 'Popover',
  'popper': 'Popper',
  'tooltip': 'Tooltip',
  '########': {
    type: 'separator',
    title: 'Отображение данных',
  },
  'accordion': 'Accordion',
  'avatar': 'Avatar',
  'badge': 'Badge',
  'banner': 'Banner',
  'card': 'Card',
  'content-badge': 'ContentBadge',
  'content-card': 'ContentCard',
  'counter': 'Counter',
  'chip': 'Chip',
  'gallery': 'Gallery',
  'grid-avatar': 'GridAvatar',
  'horizontal-cell': 'HorizontalCell',
  'horizontal-scroll': 'HorizontalScroll',
  'image': 'Image',
  'image-base': 'ImageBase',
  'info-row': 'InfoRow',
  'mini-info-cell': 'MiniInfoCell',
  'placeholder': 'Placeholder',
  'rich-cell': 'RichCell',
  'users-stack': 'UsersStack',
  '#########': {
    type: 'separator',
    title: 'Типографика',
  },
  'ellipsis-text': 'EllipsisText',
  'typography': 'Типографика',
  'mark': 'Mark',
  'link': 'Link',
  '#': {
    type: 'separator',
    title: 'Конфигурация',
  },
  'adaptivity-provider': 'AdaptivityProvider',
  'app-root': 'AppRoot',
  'color-scheme-provider': 'ColorSchemeProvider',
  'config-provider': 'ConfigProvider',
  'direction-provider': 'DirectionProvider',
  'locale-provider': 'LocaleProvider',
  'platform-provider': 'PlatformProvider',
  '###########': {
    type: 'separator',
    title: 'Утилиты',
  },
  'aspect-ratio': 'AspectRatio',
  'adaptive-icon-renderer': 'AdaptiveIconRenderer',
  'custom-scroll-view': 'CustomScrollView',
  'floating-arrow': 'FloatingArrow',
  'gradient': 'Gradient',
  'modal-root': 'ModalRoot',
  'onboarding-tooltip': 'OnboardingTooltip',
  'popout-wrapper': 'PopoutWrapper',
  'scroll-arrow': 'ScrollArrow',
  'search': 'Search',
  'selection-control': 'SelectionControl',
  'tappable': 'Tappable',
  'touch': 'Touch',
  'unstyled-text-field': 'UnstyledTextField',
  'use-adaptivity-conditional-render': 'useAdaptivityConditionalRender',
  'use-adaptivity-with-js-media-queries': 'useAdaptivityWithJSMediaQueries',
  'use-focus-visible': 'useFocusVisible',
  'use-patch-children': 'usePatchChildren',
  'use-scroll': 'useScroll',
  'use-scroll-lock': 'useScrollLock',
  'use-modal-root': 'useModalRoot',
  'use-today-date': 'useTodayDate',
  'visually-hidden': 'VisuallyHidden',
};

export default meta;
