declare const styles: {
  readonly "active": string;
  readonly "after": string;
  readonly "alignLeft": string;
  readonly "alignRight": string;
  readonly "appearanceAccent": string;
  readonly "appearanceAccentInvariable": string;
  readonly "appearanceNegative": string;
  readonly "appearanceNeutral": string;
  readonly "appearanceOverlay": string;
  readonly "appearancePositive": string;
  readonly "before": string;
  readonly "content": string;
  readonly "disabled": string;
  readonly "host": string;
  readonly "hover": string;
  readonly "in": string;
  readonly "ios": string;
  readonly "loading": string;
  readonly "modeLink": string;
  readonly "modeOutline": string;
  readonly "modePrimary": string;
  readonly "modeSecondary": string;
  readonly "modeTertiary": string;
  readonly "rounded": string;
  readonly "singleIcon": string;
  readonly "sizeL": string;
  readonly "sizeM": string;
  readonly "sizeS": string;
  readonly "sizeYNone": string;
  readonly "sizeYRegular": string;
  readonly "spinner": string;
  readonly "stretched": string;
};
export = styles;

