# Используется экшеном https://github.com/dorny/paths-filter
#
# > WARNING:
# > Для запуска линтов, не стоит завязываться на проверку расширения файлов, т.к. они не гарант успешной валидации.
# > Помимо расширений, могут быть зависимости, конфигурации, скрипты, которые могут влиять на ход работы линта.
#
# https://github.com/VKCOM/VKUI/issues/4114

# Изменение лок-файла гарантирует, что были обновлены зависимости
dependencies: &dependencies
  - 'yarn.lock'

# Отмечаем всё, что хоть как-то может повлиять на конечную сборку пакета vkui
package_vkui: &package_vkui
  - *dependencies
  - 'packages/vkui/*.!(md)'
  - 'packages/vkui/!(.storybook)src/**/!(*.md|*.mdx|*.stories.*)'
  - 'tools/!(eslint-*|stylelint-*|storybook-*)/**'
  - 'postcss.*'
  - '.browserslistrc'
  - 'webpack.*'
  - 'tsconfig.*'
  - 'package.json'

docs_styleguide:
  - *package_vkui
  - 'packages/vkui/src/**/*.md'
  - 'styleguide/**'

docs_storybook:
  - *package_vkui
  - 'packages/vkui/.storybook/**'
  - 'packages/vkui/storybook/**'
  - 'packages/vkui/src/**/*.stories.*'
  - 'packages/vkui/src/**/*.mdx'
  - 'tools/storybook-*/**'

docs_beta:
  - *package_vkui
  - 'docs-beta/**'
