name: Setup
description: It setting up the repository environment

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        always-auth: true
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: YARN_ENABLE_SCRIPTS=false yarn install --immutable
      shell: bash
