approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableScripts: true

enableTransparentWorkspaces: false

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"
