const path = require('path');
const { argv } = require('yargs');
const { makeFsImporter } = require('react-docgen/dist/importer');
const { findAllExportedComponentDefinitions } = require('react-docgen/dist/resolver');

module.exports = {
  title: 'VKUI styleguide',
  styleguideDir: path.join(__dirname, `../${argv.dist || 'docs'}`),
  styleguideComponents: {
    'PlaygroundRenderer': path.join(__dirname, './Components/Playground/PlaygroundRenderer'),
    'StyleGuide': path.join(__dirname, './Components/StyleGuide/StyleGuide'),
    'StyleGuideRenderer': path.join(__dirname, './Components/StyleGuide/StyleGuideRenderer'),
    'PathlineRenderer': path.join(__dirname, './Components/PathlineRenderer'),
    'HeadingRenderer': path.join(__dirname, './Components/Heading/HeadingRenderer'),
    'ReactComponent': path.join(__dirname, './Components/ReactComponent/ReactComponent'),
    'TableOfContents': path.join(__dirname, './Components/TableOfContents/TableOfContents'),
    'ParaRenderer': path.join(__dirname, './Components/Para/ParaRenderer'),
    'CodeRenderer': path.join(__dirname, './Components/Code/CodeRenderer'),
    'TextRenderer': path.join(__dirname, './Components/Text/TextRenderer'),
    'Section': path.join(__dirname, './Components/Section'),
    'SectionHeadingRenderer': path.join(__dirname, './Components/SectionHeading/SectionHeadingRenderer'),
    'Markdown/Blockquote': path.join(__dirname, './Components/Blockquote'),
    'Markdown/List': path.join(__dirname, './Components/List'),
    'Markdown/MarkdownHeading': path.join(__dirname, './Components/MarkdownHeading'),
    'Markdown/Pre': path.join(__dirname, './Components/Pre'),
    'TableRenderer': path.join(__dirname, './Components/Table/TableRenderer'),
    'LinkRenderer': path.join(__dirname, './Components/Link/LinkRenderer'),
    'NameRenderer': path.join(__dirname, './Components/Name/NameRenderer'),
    'TypeRenderer': path.join(__dirname, './Components/Type/TypeRenderer'),
    'ComplexType/ComplexTypeRenderder': path.join(__dirname, './Components/ComplexType/ComplexTypeRenderder'),
    'Preview': path.join(__dirname, './Components/Preview'),
    'Editor': path.join(__dirname, './Components/Editor'),
  },
  propsParser: (filePath, source) => {
    return require('react-docgen').parse(source, findAllExportedComponentDefinitions, null, {
      filename: filePath,
      importer: makeFsImporter(),
    });
  },
  exampleMode: 'expand',
  assetsDir: path.join(__dirname, `assets`),
  sections: [{
    title: 'О VKUI',
    name: 'About',
    content: './pages/intro.md',
  }, {
    title: 'Быстрый старт',
    name: 'QuickStart',
    content: './pages/quick_start.md',
  }, {
    title: 'Основа',
    name: 'Basics',
    expand: true,
    sections: [{
      title: 'Режимы подключения',
      name: 'Modes',
      content: './pages/modes.md',
    }, {
      title: 'Адаптивность',
      name: 'Adaptivity',
      content: './pages/adaptivity.md',
    }, {
      title: 'Платфомы и темы',
      name: 'PlatformsAndThemes',
      content: './pages/platforms_and_themes.md',
    }, {
      title: 'Структура экранов',
      name: 'Structure',
      content: './pages/structure.md',
    }],
  }, {
      name: 'Компоненты',
      sectionDepth: 2,
      expand: true,
      search: true,
      sections: [{
        name: 'Layout',
        components: [
          '../src/components/SplitLayout/SplitLayout.tsx',
          '../src/components/SplitCol/SplitCol.tsx',
          '../src/components/Root/Root.tsx',
          '../src/components/View/View.tsx',
          '../src/components/Panel/Panel.tsx',
          '../src/components/PanelHeader/PanelHeader.tsx',
          '../src/components/PanelHeaderButton/PanelHeaderButton.tsx',
          '../src/components/PanelHeaderBack/PanelHeaderBack.tsx',
          '../src/components/PanelHeaderClose/PanelHeaderClose.tsx',
          '../src/components/PanelHeaderSubmit/PanelHeaderSubmit.tsx',
          '../src/components/PanelHeaderEdit/PanelHeaderEdit.tsx',
          '../src/components/PanelHeaderContent/PanelHeaderContent.tsx',
          '../src/components/PanelHeaderContext/PanelHeaderContext.tsx',
          '../src/components/Epic/Epic.tsx',
          '../src/components/Tabbar/Tabbar.tsx',
          '../src/components/TabbarItem/TabbarItem.tsx',
          '../src/components/FixedLayout/FixedLayout.tsx',
          '../src/components/HorizontalScroll/HorizontalScroll.tsx',
        ],
      }, {
        name: 'Popouts',
        components: () => [
          '../src/components/PopoutWrapper/PopoutWrapper.tsx',
          '../src/components/ActionSheet/ActionSheet.tsx',
          '../src/components/ActionSheetItem/ActionSheetItem.tsx',
          '../src/components/Alert/Alert.tsx',
          '../src/components/ScreenSpinner/ScreenSpinner.tsx',
          '../src/components/Snackbar/Snackbar.tsx',
        ],
      }, {
        name: 'Modals',
        components: () => [
          '../src/components/ModalRoot/ModalRootAdaptive.tsx',
          '../src/components/ModalPage/ModalPage.tsx',
          '../src/components/ModalPageHeader/ModalPageHeader.tsx',
          '../src/components/ModalCard/ModalCard.tsx',
          '../src/components/ModalDismissButton/ModalDismissButton.tsx',
        ],
      }, {
        name: 'Blocks',
        components: () => [
          '../src/components/Badge/Badge.tsx',
          '../src/components/Button/Button.tsx',
          '../src/components/CellButton/CellButton.tsx',
          '../src/components/IconButton/IconButton.tsx',
          '../src/components/Div/Div.tsx',
          '../src/components/Link/Link.tsx',
          '../src/components/Header/Header.tsx',
          '../src/components/Group/Group.tsx',
          '../src/components/Card/Card.tsx',
          '../src/components/CardGrid/CardGrid.tsx',
          '../src/components/CardScroll/CardScroll.tsx',
          '../src/components/ContentCard/ContentCard.tsx',
          '../src/components/Gradient/Gradient.tsx',
          '../src/components/SimpleCell/SimpleCell.tsx',
          '../src/components/Cell/Cell.tsx',
          '../src/components/HorizontalCell/HorizontalCell.tsx',
          '../src/components/RichCell/RichCell.tsx',
          '../src/components/List/List.tsx',
          '../src/components/Footer/Footer.tsx',
          '../src/components/Spinner/Spinner.tsx',
          '../src/components/PanelSpinner/PanelSpinner.tsx',
          '../src/components/Switch/Switch.tsx',
          '../src/components/InfoRow/InfoRow.tsx',
          '../src/components/Avatar/Avatar.tsx',
          '../src/components/Gallery/Gallery.tsx',
          '../src/components/Progress/Progress.tsx',
          '../src/components/Search/Search.tsx',
          '../src/components/Tabs/Tabs.tsx',
          '../src/components/TabsItem/TabsItem.tsx',
          '../src/components/Tooltip/Tooltip.tsx',
          '../src/components/PullToRefresh/PullToRefresh.tsx',
          '../src/components/Counter/Counter.tsx',
          '../src/components/UsersStack/UsersStack.tsx',
          '../src/components/Spacing/Spacing.tsx',
          '../src/components/Separator/Separator.tsx',
          '../src/components/Placeholder/Placeholder.tsx',
          '../src/components/Banner/Banner.tsx',
          '../src/components/MiniInfoCell/MiniInfoCell.tsx',
          '../src/components/WriteBar/WriteBar.tsx',
          '../src/components/WriteBarIcon/WriteBarIcon.tsx',
          '../src/components/SubnavigationBar/SubnavigationBar.tsx',
          '../src/components/SubnavigationButton/SubnavigationButton.tsx',
          '../src/components/ModalCardBase/ModalCardBase.tsx',
        ],
      }, {
        name: 'Forms',
        components: () => [
          '../src/components/FormLayout/FormLayout.tsx',
          '../src/components/FormItem/FormItem.tsx',
          '../src/components/FormLayoutGroup/FormLayoutGroup.tsx',
          '../src/components/FormStatus/FormStatus.tsx',
          '../src/components/Slider/Slider.tsx',
          '../src/components/RangeSlider/RangeSlider.tsx',
          '../src/components/Radio/Radio.tsx',
          '../src/components/Checkbox/Checkbox.tsx',
          '../src/components/Input/Input.tsx',
          '../src/components/ChipsInput/ChipsInput.tsx',
          '../src/components/Select/Select.tsx',
          '../src/components/NativeSelect/NativeSelect.tsx',
          '../src/components/SelectMimicry/SelectMimicry.tsx',
          '../src/components/CustomSelect/CustomSelect.tsx',
          '../src/components/CustomSelectOption/CustomSelectOption.tsx',
          '../src/components/ChipsSelect/ChipsSelect.tsx',
          '../src/components/Chip/Chip.tsx',
          '../src/components/Textarea/Textarea.tsx',
          '../src/components/File/File.tsx',
          '../src/components/DatePicker/DatePicker.tsx',
          '../src/components/SliderSwitch/SliderSwitch.tsx',
        ],
      }, {
        name: 'Typography',
        components: () => [
          '../src/components/Typography/Title/Title.tsx',
          '../src/components/Typography/Headline/Headline.tsx',
          '../src/components/Typography/Text/Text.tsx',
          '../src/components/Typography/Subhead/Subhead.tsx',
          '../src/components/Typography/Caption/Caption.tsx',
        ],
      }, {
        name: 'Advertisement',
        components: () => ['../src/components/PromoBanner/PromoBanner.tsx'],
      }, {
        name: 'Service',
        components: () => [
          '../src/components/AppRoot/AppRoot.tsx',
          '../src/components/AdaptivityProvider/AdaptivityProvider.tsx',
          '../src/components/ConfigProvider/ConfigProvider.tsx',
          '../src/components/Touch/Touch.tsx',
        ],
      }],
    }, {
      name: 'Прочее',
      expand: true,
      sectionDepth: 1,
      sections: [{
        name: 'Unstable',
        content: './pages/unstable.md',
      }, {
        name: 'Helpers',
        content: './pages/helpers.md',
      },
      {
        title: 'Серверный рендеринг',
        name: 'SSR',
        content: './pages/ssr.md',
      },
      {
        title: 'Иконки',
        name: 'Icons',
        content: './pages/icons.md',
      }, {
        title: 'Утилиты',
        name: 'Utils',
        content: './pages/utils.md',
      }, {
        title: 'Дизайн',
        name: 'Design',
        content: './pages/design.md',
      }],
    },
  ],
  require: [
    path.resolve(__dirname, './setup.js'),
    path.resolve(__dirname, './setup.css'),
  ],
  webpackConfig: require('./webpack.config'),
};
