declare const styles: {
  readonly "blockIndent2xl": string;
  readonly "blockIndent2xs": string;
  readonly "blockIndent3xl": string;
  readonly "blockIndent4xl": string;
  readonly "blockIndentL": string;
  readonly "blockIndentM": string;
  readonly "blockIndentS": string;
  readonly "blockIndentXl": string;
  readonly "blockIndentXs": string;
  readonly "hidden": string;
  readonly "host": string;
  readonly "inlineIndent2xl": string;
  readonly "inlineIndent2xs": string;
  readonly "inlineIndent3xl": string;
  readonly "inlineIndent4xl": string;
  readonly "inlineIndentL": string;
  readonly "inlineIndentM": string;
  readonly "inlineIndentS": string;
  readonly "inlineIndentXl": string;
  readonly "inlineIndentXs": string;
  readonly "placementBottom": string;
  readonly "placementBottomEnd": string;
  readonly "placementBottomStart": string;
  readonly "placementMiddle": string;
  readonly "placementMiddleEnd": string;
  readonly "placementMiddleStart": string;
  readonly "placementTop": string;
  readonly "placementTopEnd": string;
  readonly "placementTopStart": string;
};
export = styles;

