name: Check that file was changed

inputs:
  file_path:
    description: path to file
    required: true

outputs:
  result:
    value: ${{ steps.check_changes.result }}

runs:
  using: composite
  steps:
    - name: Check for changes in file
      id: check_changes
      run: |
        if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -q "^${{ inputs.file_path }}$"; then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
        fi
