name: 'S3'
description: 'S3 commands'
inputs:
  awsAccessKeyId:
    required: true
    description: 'aws accessKeyId'
  awsSecretAccessKey:
    required: true
    description: 'aws secretAccessKey'
  awsBucket:
    required: true
    description: 'awsBucket'
  awsRegion:
    required: false
    description: 'awsRegion'
  awsEndpoint:
    required: false
    description: 'endpoint'

  command:
    required: true
    description: 'upload or delete'

  commandUploadSrc:
    required: false
    description: ''
  commandUploadDist:
    required: false
    description: ''

  commandDeletePrefix:
    required: false
    description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
