name: Publish Workflow / Validation
description: It runs pre-publish checks

inputs:
  package_name:
    description: package's name
    required: true

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: Run linters
      run: yarn run lint

    - name: Run build
      run: yarn workspace ${{ inputs.package_name }} run build

    - name: Run tests and linters
      run: yarn workspace ${{ inputs.package_name }} run test
