name: Workflow / Checkout LFS objects
description: Get lfs from cache

inputs:
  apt_mirror:
    description: apt mirror
  sudo_cmd:
    description: Command prefix for privileged operations
    default: sudo

runs:
  using: composite
  steps:
    # см. https://github.com/actions/checkout/issues/1169
    - name: Set safe directory
      shell: bash
      run: git config --global --add safe.directory /__w/VKUI/VKUI


    - name: Configure apt mirror
      if: ${{ inputs.apt_mirror }}
      shell: bash
      run: |
        ${{ inputs.sudo_cmd }} sed -i "s|http://archive.ubuntu.com|${{ inputs.apt_mirror }}|g" /etc/apt/sources.list
        ${{ inputs.sudo_cmd }} sed -i "s|http://security.ubuntu.com|${{ inputs.apt_mirror }}|g" /etc/apt/sources.list
        ${{ inputs.sudo_cmd }} apt-get update

    # см. https://github.com/microsoft/playwright/issues/21920
    - name: Install git lfs
      shell: bash
      run: |
        if git lfs > /dev/null ; then
          echo "git-lfs installed"
        else
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | ${{ inputs.sudo_cmd }} bash
          ${{ inputs.sudo_cmd }} apt-get install -y git-lfs
        fi

    # см. https://github.com/actions/cache/issues/1455
    - name: Install zstd
      shell: bash
      run: |
        if zstd > /dev/null ; then
          echo "zstd installed"
        else
          ${{ inputs.sudo_cmd }} apt-get install -y zstd
        fi

    - name: Create LFS file list
      shell: bash
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v4
      with:
        path: .git/lfs
        key: lfs-${{ hashFiles('.lfs-assets-id') }}
        enableCrossOsArchive: 'true'

    - name: Checkout LFS objects
      shell: bash
      run: git lfs pull
