name: Create pull request
description: Create pull request

inputs:
  token:
    description: token for write access to repository
    required: true
  title:
    description: title of pull request
    required: true
  body:
    description: body of pull request
    required: true
  head:
    description: head of pull request
    required: true
  base:
    description: base of pull request
    required: true

outputs:
  pull_request_number:
    value: ${{ steps.create_pull_request.outputs.pull_request_number }}

runs:
  using: composite
  steps:
    - name: Create pull request
      id: create_pull_request
      uses: actions/github-script@v7
      with:
        script: |
          const octokit = github.getOctokit(${{ inputs.token }});
          const { owner, repo } = github.context.repo;
          const { data: pr } = await octokit.rest.pulls.create({
            owner,
            repo,
            title: ${{ inputs.title }},
            body: ${{ inputs.body }},
            head: ${{ inputs.head }},
            base: ${{ inputs.base }},
          });

          core.setOutput('pull_request_number', pr.number);
