name: Add Label to pull request
description: Adds a label to a pull request

inputs:
  issue_number:
    description: number of issue
    required: true
  label:
    description: label to adding
    required: true

runs:
  using: composite
  steps:
    - name: Add label
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: ${{ inputs.issue_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ["${{ inputs.label }}"]
          })
