name: 'Stable branch'
description: 'GitLab Flow create stable branch'
inputs:
  token:
    required: true
    description: 'token with access to your repository'
runs:
  using: 'node16'
  main: 'dist/index.js'
