nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: 'https://registry.npmjs.org'

# specially for @vkontakte/floating-ui-react-dom package
# to use published version instead of workspace by default
enableTransparentWorkspaces: false

compressionLevel: mixed
