import * as index_d from '../external/monaco-lsp-client/out/index.js';
export { index_d as lsp };
import * as __src_languages_features_css_register_ts from './languages/features/css/register.js';
export { __src_languages_features_css_register_ts as css };
import * as __src_languages_features_html_register_ts from './languages/features/html/register.js';
export { __src_languages_features_html_register_ts as html };
import * as __src_languages_features_json_register_ts from './languages/features/json/register.js';
export { __src_languages_features_json_register_ts as json };
import * as __src_languages_features_typescript_register_ts from './languages/features/typescript/register.js';
export { __src_languages_features_typescript_register_ts as typescript };
export { CancellationToken, CancellationTokenSource, Emitter, Environment, IDisposable, IEvent, IKeyboardEvent, IMarkdownString, IMouseEvent, IPosition, IRange, IScrollEvent, ISelection, ITrustedTypePolicy, ITrustedTypePolicyOptions, KeyCode, KeyMod, MarkdownStringTrustedOptions, MarkerSeverity, MarkerTag, Position, Range, Selection, SelectionDirection, Thenable, Token, Uri, UriComponents, editor, languages, worker } from './editor/editor.api.js';
