name: Publish Workflow / Complete
description: It finish publishing

inputs:
  branch:
    description: target branch for git push
    required: true
  prev_version:
    description: package's prev version
    required: true
  next_version:
    description: package's next version
    required: true
  package_name:
    description: package's name
    required: true
  token:
    description: token for write access to repository
    required: true
  npm_tag:
    description: tag for NPM artifact
    required: false
    default: latest
  disable_git_tag_with_namespace:
    description: Whether to omit package name from git tag
    required: false
    default: false
  close_milestone:
    description: Whether to close the milestone after publishing
    required: false
    default: false
  prerelease:
    description: Whether the published version is a prerelease
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Commit
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
        PREV_VERSION: ${{ inputs.prev_version }}
        NEXT_VERSION: ${{ inputs.next_version }}
      run: |
        git add -A
        git commit -m "bump(${PACKAGE_NAME}): from ${PREV_VERSION} to ${NEXT_VERSION}"
      shell: bash

    - name: Create git tag
      id: git_release_tag
      env:
        DISABLE_GIT_TAG_WITH_NAMESPACE: ${{ inputs.disable_git_tag_with_namespace }}
        NEXT_VERSION: ${{ inputs.next_version }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        if [[ "$DISABLE_GIT_TAG_WITH_NAMESPACE" == "true" ]]; then
          GIT_TAG="v${NEXT_VERSION}"
        else
          GIT_TAG="${PACKAGE_NAME}@${NEXT_VERSION}"
        fi

        git tag "$GIT_TAG"
        printf 'value=%s\n' "$GIT_TAG" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Generate archive
      # ../../ – это путь до корня из директории `packages/<name>`
      env:
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: yarn workspace "$PACKAGE_NAME" pack --out ../../artifact.tgz
      shell: bash

    - name: Publishing release
      env:
        NPM_TAG: ${{ inputs.npm_tag }}
      run: |
        npm publish artifact.tgz --tag "$NPM_TAG"
      shell: bash

    - name: Pushing changes
      uses: ad-m/github-push-action@4cc74773234f74829a8c21bc4d69dd4be9cfa599 # v1.1.0
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        tags: true

    - name: Create stable branch
      uses: VKCOM/gh-actions/VKUI/stable-branch@main
      if: ${{ inputs.package_name == '@vkontakte/vkui' && fromJSON(inputs.prerelease) == false }}
      with:
        token: ${{ inputs.token }}
        directory: packages/vkui/

    - name: Prepare payload data
      env:
        BRANCH: ${{ inputs.branch }}
        CLOSE_MILESTONE: ${{ inputs.close_milestone }}
        GIT_RELEASE_TAG: ${{ steps.git_release_tag.outputs.value }}
        NEXT_VERSION: ${{ inputs.next_version }}
        NPM_TAG: ${{ inputs.npm_tag }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        mkdir -p publish_workflow_payload
        printf '%s\n' "$NEXT_VERSION" > publish_workflow_payload/next_version.txt
        printf '%s\n' "$PACKAGE_NAME" > publish_workflow_payload/package_name.txt
        printf '%s\n' "$NPM_TAG" > publish_workflow_payload/npm_tag.txt
        printf '%s\n' "$GIT_RELEASE_TAG" > publish_workflow_payload/git_release_tag.txt
        printf '%s\n' "$CLOSE_MILESTONE" > publish_workflow_payload/close_milestone.txt
        printf '%s\n' "$BRANCH" > publish_workflow_payload/branch.txt
      shell: bash

    - name: Upload payload data to artifact for deploy workflow
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: publish_workflow_payload
        path: publish_workflow_payload/
        retention-days: 1
