name: Publish Workflow / Complete
description: It finish publishing

inputs:
  branch:
    description: target branch for git push
    required: true
  prev_version:
    description: package's prev version
    required: true
  next_version:
    description: package's next version
    required: true
  package_name:
    description: package's name
    required: true
  token:
    description: token for write access to repository
    required: true
  npm_token:
    description: token for publish package to NPM
    required: true
  npm_tag:
    description: tag for NPM artifact
    required: false
    default: latest
  disable_git_tag_with_namespace:
    required: false
    default: false
  close_milestone:
    required: false
    default: false
  prerelease:
    required: false
    default: false

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: Commit
      run: |
        git add -A
        git commit -m 'bump(${{ inputs.package_name }}): from ${{ inputs.prev_version }} to ${{ inputs.next_version }}'

    - name: Create git tag
      id: git_release_tag
      run: |
        GIT_TAG=${{ fromJSON(inputs.disable_git_tag_with_namespace) == true && format('v{0}', inputs.next_version) || format('{0}@{1}', inputs.package_name, inputs.next_version) }}
        git tag $GIT_TAG
        echo "value=$GIT_TAG" >> $GITHUB_OUTPUT

    - name: Generate archive
      # ../../ – это путь до корня из директории `packages/<name>`
      run: yarn workspace ${{ inputs.package_name }} pack --out ../../artifact.tgz

    - name: Publishing release
      run: |
        npm publish artifact.tgz --tag ${{ inputs.npm_tag }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}

    - name: Pushing changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        tags: true

    - name: Create stable branch
      uses: VKCOM/gh-actions/VKUI/stable-branch@main
      if: ${{ inputs.package_name == '@vkontakte/vkui' && fromJSON(inputs.prerelease) == false }}
      with:
        token: ${{ inputs.token }}
        directory: packages/vkui/

    - name: Prepare payload data
      run: |
        mkdir -p publish_workflow_payload
        echo ${{ inputs.next_version }} > publish_workflow_payload/next_version.txt
        echo ${{ inputs.package_name }} > publish_workflow_payload/package_name.txt
        echo ${{ inputs.npm_tag }} > publish_workflow_payload/npm_tag.txt
        echo ${{ steps.git_release_tag.outputs.value }} > publish_workflow_payload/git_release_tag.txt
        echo ${{ inputs.close_milestone }} > publish_workflow_payload/close_milestone.txt

    - name: Upload payload data to artifact for deploy workflow
      uses: actions/upload-artifact@v4
      with:
        name: publish_workflow_payload
        path: publish_workflow_payload/
        retention-days: 1
