name: Publish Workflow / Setup
description: It setting up the repository environment for publish

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        always-auth: true
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: YARN_ENABLE_SCRIPTS=false yarn install --immutable --check-cache --check-resolutions
      shell: bash

    - name: Set Git credentials
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
      shell: bash
