name: Add next minor milestone to pull request
description: Add next minor milestone to pull request

inputs:
  pull_request_number:
    description: number of pull request
    required: true

runs:
  using: composite
  steps:
    - name: Add milestone to PR
      uses: VKCOM/gh-actions/VKUI/add-next-minor-milestone@main
      with:
        token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
        pull_request_number: ${{ inputs.pull_request_number }}
