name: Workflow / Setup NodeJS
description: It setting up the NodeJS

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Setup NodeJS
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Install dependencies
      run: YARN_ENABLE_SCRIPTS=false YARN_ENABLE_HARDENED_MODE=0 yarn install --immutable
      shell: bash
