#
# Требования:
# - Тесты должны запускаться при каждом изменении в ветке, чтобы корректно рассчитывалось покрытие тестами при
#   последующих изменениях.
# - В джобах точечно указываем пакеты, для которых проверяется покрытие.
#

name: Branch test coverage

run-name: Check ${{ github.ref_name }} branch test coverage

on:
  push:
    branches:
      - master
      - '*-stable'

concurrency:
  group: branch-test-coverage-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Создаем кэш для LFS в мастере, чтобы другие ветки могли его получить.
  # Кэш требуется для того, чтобы не превышать лимиты GitHub
  lfs:
    runs-on: ubuntu-slim
    name: Create LFS cache
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Checkout LFS objects
        uses: ./.github/actions/lfs
        with:
          apt_mirror: ${{ vars.APT_MIRROR }}

  test:
    name: Call reusable unit tests workflow
    uses: ./.github/workflows/reusable_workflow_test.yml
    with:
      workspace: '@vkontakte/vkui'

  deploy_test_coverage:
    if: ${{ !cancelled() && (success() || failure()) }}
    needs: test
    runs-on: ubuntu-slim
    name: Deploy test coverage
    permissions:
      id-token: write
      code-quality: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download test artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: test-output

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          flags: unittests
          files: .nyc_output/coverage-final.json
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage to GitHub
        uses: actions/upload-code-coverage@abb5995db9e0199b0e2bb9dbd136fce4cb1ec4d3 # v1.3.0
        with:
          file: .nyc_output/cobertura-coverage.xml
          language: TypeScript
          label: code-coverage/vitest
