name: 'Deduplicate dependencies'

on:
  workflow_dispatch:
    inputs:
      push_directly:
        description: 'push directly to the branch'
        type: boolean
        default: false

run-name: Deduplicate dependencies on ${{ github.ref_name }}

jobs:
  dedupe_deps:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Node setup
        uses: ./.github/actions/node-setup

      - name: Dedupe deps
        run: yarn dedupe

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Create pull request with deduped deps
        if: ${{ inputs.push_directly != true }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          title: 'chore: Deduplicate dependencies on ${{ github.ref_name }}'
          branch: ${{ github.ref_name }}-dedupe-deps
          commit-message: 'chore: deduplicate dependencies'
          body: Automated dependencies deduplication
          delete-branch: true

      - name: Commit files
        if: ${{ inputs.push_directly == true }}
        run: |
          git commit -a -m "chore: deduplicate dependencies"

      - name: Push changes to the branch directly
        if: ${{ inputs.push_directly == true }}
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          github_token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
