name: Dependabot PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-dependabot-pr:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: ./.github/actions/node-setup

      - name: Report lint results
        if: ${{ !cancelled() }}
        uses: VKCOM/gh-actions/VKUI/add-dependabot-pr-milestone@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
