name: 'Deploy docs from specific branch'

on: workflow_dispatch

run-name: Deploy docs from ${{ github.ref_name }}

permissions:
  contents: read

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    name: Build and deploy docs
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/node-setup

      - name: Build VKUI
        run: node --run build:vkui

      - name: Build docs
        run: |
          node --run docs:website:build
          yarn workspace @project-docs/website next-sitemap

      - name: Publishing docs
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: gh-pages
          folder: website/out
          clean: true
          clean-exclude: |
            [0-9].[0-9].[0-9]/
            playground/
          force: false
