name: 'Deploy docs from specific branch'

on: workflow_dispatch

run-name: Deploy docs from ${{ github.ref_name }}

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    name: Build and deploy docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: ./.github/actions/node-setup

      - name: Build VKUI
        run: yarn build:vkui

      - name: Build docs
        run: yarn docs:beta:build

      - name: Publishing docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: VKCOM/vkui.io
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          branch: main
          folder: website/out
          clean: true
          clean-exclude: |
            [0-9].[0-9].[0-9]/
            playground/
          force: false
