name: 'Cron / Monday'
on:
  schedule:
    - cron: '0 5 * * 1' # Runs at 05:00, only on Monday

jobs:
  tools-update:
    name: Tools update
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Node setup
        uses: ./.github/actions/node-setup

      - uses: VKCOM/gh-actions/shared/node/corepack-up-pr@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - uses: VKCOM/gh-actions/shared/node/nvmrc-up-pr@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
