name: 'Cron / Monday'
on:
  schedule:
    - cron: '0 5 * * 1' # Runs at 05:00, only on Monday

jobs:
  tools-update:
    name: Tools update
    runs-on: ubuntu-slim
    # Note: для работы corepack-up-pr и nvmrc-up-pr нужны права на write
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Node setup
        uses: ./.github/actions/node-setup

      - uses: VKCOM/gh-actions/shared/node/corepack-up-pr@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - uses: VKCOM/gh-actions/shared/node/nvmrc-up-pr@main
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
