name: 'Publish @vkontakte/vkui-floating-ui'

on:
  workflow_dispatch:

run-name: "@vkontakte/vkui-floating-ui: deprecate 0.2.0"

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/vkui-floating-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: NPM it
        run: |
          npm deprecate @vkontakte/vkui-floating-ui@0.2.0 "This is a duplicate of the version 'v0.1.4'. Use 'v0.1.4' and above. Due to this typo, the stable minor version will be released as 'v0.2.1'."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
