name: 'Publish @vkontakte/vkui-codemods'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'codemods version (without v)'
        required: true

run-name: Publish codemods@${{ inputs.version }}

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/codemods
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: YARN_ENABLE_SCRIPTS=false yarn install --immutable

      - name: Run tests
        run: yarn run test

      - name: Build package
        run: yarn run build

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Saving current version to env
        id: prev_version
        run: |
          echo "version=$(yarn node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bump version
        run: yarn run g:npm:version ${{ github.event.inputs.version }}

      - name: Saving updated version to env
        id: updated_version
        run: |
          echo "version=$(yarn node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Adding commit and tag with updated version number
        run: |
          git add -A
          git commit -m 'bump(@vkontakte/vkui-codemods): from ${{ steps.prev_version.outputs.version }} to ${{ steps.updated_version.outputs.version }}'
          git tag @vkontakte/vkui-codemods@${{ steps.updated_version.outputs.version }}

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Generate archive
        run: yarn pack

      - name: Publishing release
        run: |
          npm publish package.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
