name: 'Publish @vkontakte/vkui-floating-ui'

on:
  workflow_dispatch:

run-name: "@vkontakte/vkui-floating-ui: remove alpha tag"

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/vkui-floating-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: YARN_ENABLE_SCRIPTS=false yarn install --immutable

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Publishing tagged release
        run: |
          npm dist-tag rm @vkontakte/vkui-floating-ui alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
