name: 'Publish @vkontakte/vkui-floating-ui'

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'version type. Choose empty option if using custom version'
        type: choice
        default: 'minor'
        options:
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
          - ~
        required: true
      custom_version:
        description: 'custom version: x.y.z-preid.a (without "v"). Overrides version type'
        required: false
      tag:
        description: 'prerelease tag: preid ("alpha" or "beta"). Leave empty for release'
        required: false

run-name: Publish @vkontakte/vkui-floating-ui ${{ inputs.custom_version }} ${{ inputs.type }} ${{ inputs.tag }}

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/vkui-floating-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: YARN_ENABLE_SCRIPTS=false yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Set Git credentials
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Saving current version to env
        id: prev_version
        run: echo "version=$(yarn node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bumping @vkontakte/vkui-floating-ui version via version type
        if: ${{ !github.event.inputs.custom_version }}
        run: |
          yarn run g:npm:version ${{ github.event.inputs.type }} --preid ${{ github.event.inputs.tag }}

      - name: Bumping @vkontakte/vkui-floating-ui version via custom version
        if: ${{ github.event.inputs.custom_version }}
        run: |
          yarn run g:npm:version ${{ github.event.inputs.custom_version }} --preid ${{ github.event.inputs.tag }}

      - name: Saving updated version to env
        id: updated_version
        run: echo "version=$(yarn node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Adding commit and tag with updated version number
        run: |
          git add -A
          git commit -m 'bump(@vkontakte/vkui-floating-ui): from ${{ steps.prev_version.outputs.version }} to ${{ steps.updated_version.outputs.version }}'
          git tag @vkontakte/vkui-floating-ui@${{ steps.updated_version.outputs.version }}

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Generate archive
        run: yarn pack

      - name: Publishing tagged release
        if: ${{ github.event.inputs.tag }}
        run: |
          npm publish package.tgz --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}

      - name: Publishing release
        if: ${{ !github.event.inputs.tag }}
        run: |
          npm publish package.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
