name: 'Pull Request / Packages: Deploy'
# Note: display_title не задокументирован
run-name: '${{ github.event.workflow_run.display_title }} • ${{ github.event.workflow_run.head_branch }} • ${{ github.event.workflow_run.id }}'

on:
  workflow_run:
    workflows: ['Pull Request / Packages']
    types: [completed]

env:
  PR_HEAD_REPOSITORY_FULL_NAME: ${{ github.event.workflow_run.head_repository.full_name }}
  PR_HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
  PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
  AWS_S3_URL: https://${{ vars.AWS_BUCKET }}.${{ vars.AWS_ENDPOINT }}

permissions:
  contents: read

jobs:
  pr_workflow_payload:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_repository.full_name == github.repository }}
    name: Call reusable workflow
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/reusable_workflow_pr_worfklow_payload.yml
    with:
      action: download

  deploy_test_coverage:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-slim
    name: Deploy test coverage
    permissions:
      actions: read
      id-token: write
      code-quality: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: ${{ env.PR_HEAD_REPOSITORY_FULL_NAME }}
          ref: ${{ env.PR_HEAD_SHA }}
          persist-credentials: false

      - name: Download artifact
        id: artifact
        uses: VKCOM/gh-actions/shared/download-workflow-artifact@main
        with:
          name: test-output

      - name: Upload coverage to Codecov
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          flags: unittests
          files: .nyc_output/coverage-final.json
          override_branch: ${{ env.PR_HEAD_BRANCH }}
          override_commit: ${{ env.PR_HEAD_SHA }}
          override_pr: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage to GitHub
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        uses: actions/upload-code-coverage@abb5995db9e0199b0e2bb9dbd136fce4cb1ec4d3 # v1.3.0
        with:
          file: .nyc_output/cobertura-coverage.xml
          language: TypeScript
          label: code-coverage/vitest

  deploy_playwright_report:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-slim
    name: Deploy Playwright Report and create comment
    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Download artifact
        id: artifact
        uses: VKCOM/gh-actions/shared/download-workflow-artifact@main
        with:
          name: playwright-report
          path: playwright-report/

      - name: Deploy Playwright Report
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        id: deploy
        uses: VKCOM/gh-actions/VKUI/s3@main
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsEndpoint: https://${{ vars.AWS_ENDPOINT }}
          command: upload
          commandUploadSrc: playwright-report/
          commandUploadDist: pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/playwright-report

      - name: Report
        if: ${{ steps.deploy.outcome == 'success' }}
        uses: VKCOM/gh-actions/VKUI/reporter@main
        with:
          prNumber: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          playwrightReportURL: ${{ env.AWS_S3_URL }}/pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/playwright-report/index.html
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy_docs_website:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-slim
    name: Deploy docs
    permissions:
      actions: read
      contents: read
    outputs:
      url: ${{ steps.url.outputs.value }}
    steps:
      - name: Download dist artifact
        id: artifact
        uses: VKCOM/gh-actions/shared/download-workflow-artifact@main
        with:
          name: docs-website-dist
          path: docs-website-dist/

      - name: Upload docs S3
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        id: deploy
        uses: VKCOM/gh-actions/VKUI/s3@main
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsEndpoint: https://${{ vars.AWS_ENDPOINT }}
          command: upload
          commandUploadSrc: docs-website-dist/
          commandUploadDist: pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}

      - name: Create doc url
        if: ${{ steps.deploy.outcome == 'success' }}
        id: url
        env:
          AWS_S3_URL: ${{ env.AWS_S3_URL }}
          PR_HEAD_SHA: ${{ env.PR_HEAD_SHA }}
          PR_NUMBER: ${{ needs.pr_workflow_payload.outputs.pr_number }}
        run: printf 'value=%s\n' "${AWS_S3_URL}/pull/${PR_NUMBER}/${PR_HEAD_SHA}/overview/about/index.html" >> "$GITHUB_OUTPUT"

  deploy_storybook:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-slim
    name: Deploy docs (storybook)
    permissions:
      actions: read
      contents: read
    outputs:
      url: ${{ steps.url.outputs.value }}
    steps:
      - name: Download dist artifact
        id: artifact
        uses: VKCOM/gh-actions/shared/download-workflow-artifact@main
        with:
          name: storybook-dist
          path: storybook-dist/

      - name: Upload
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        id: deploy
        uses: VKCOM/gh-actions/VKUI/s3@main
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsEndpoint: https://${{ vars.AWS_ENDPOINT }}
          command: upload
          commandUploadSrc: storybook-dist/
          commandUploadDist: pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/playground

      - name: Create doc url
        if: ${{ steps.deploy.outcome == 'success' }}
        id: url
        env:
          AWS_S3_URL: ${{ env.AWS_S3_URL }}
          PR_HEAD_SHA: ${{ env.PR_HEAD_SHA }}
          PR_NUMBER: ${{ needs.pr_workflow_payload.outputs.pr_number }}
        run: printf 'value=%s\n' "${AWS_S3_URL}/pull/${PR_NUMBER}/${PR_HEAD_SHA}/playground/index.html" >> "$GITHUB_OUTPUT"

  deploy_package:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-slim
    name: Deploy package
    permissions:
      actions: read
      contents: read
    outputs:
      url: ${{ steps.url.outputs.value }}
    steps:
      - name: Download package artifact
        id: artifact
        uses: VKCOM/gh-actions/shared/download-workflow-artifact@main
        with:
          name: package
          path: out/

      - name: Upload
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        id: deploy
        uses: VKCOM/gh-actions/VKUI/s3@main
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsEndpoint: https://${{ vars.AWS_ENDPOINT }}
          command: upload
          commandUploadSrc: out/
          commandUploadDist: pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/pkg/@vkontakte/vkui

      - name: Create doc url
        if: ${{ steps.deploy.outcome == 'success' }}
        id: url
        env:
          AWS_S3_URL: ${{ env.AWS_S3_URL }}
          PR_HEAD_SHA: ${{ env.PR_HEAD_SHA }}
          PR_NUMBER: ${{ needs.pr_workflow_payload.outputs.pr_number }}
        run: printf 'value=%s\n' "${AWS_S3_URL}/pull/${PR_NUMBER}/${PR_HEAD_SHA}/pkg/@vkontakte/vkui/_pkg.tgz" >> "$GITHUB_OUTPUT"

  deploy_diff:
    needs: pr_workflow_payload
    if: ${{ needs.pr_workflow_payload.outputs.status == 'success' }}
    runs-on: ubuntu-slim
    name: Deploy diff
    permissions:
      actions: read
      contents: read
    outputs:
      has_diff: ${{ steps.artifact.outputs.found_artifact }}
      url: ${{ steps.url.outputs.value }}
    steps:
      - name: Download package artifact
        id: artifact
        uses: VKCOM/gh-actions/shared/download-workflow-artifact@main
        with:
          name: diff-report
          path: diff/

      - name: Upload
        if: ${{ steps.artifact.outputs.found_artifact == 'true' }}
        id: deploy
        uses: VKCOM/gh-actions/VKUI/s3@main
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_KEY }}
          awsBucket: ${{ vars.AWS_BUCKET }}
          awsEndpoint: https://${{ vars.AWS_ENDPOINT }}
          command: upload
          commandUploadSrc: diff/
          commandUploadDist: pull/${{ needs.pr_workflow_payload.outputs.pr_number }}/${{ env.PR_HEAD_SHA }}/diff

      - name: Create doc url
        if: ${{ steps.deploy.outcome == 'success' }}
        id: url
        env:
          AWS_S3_URL: ${{ env.AWS_S3_URL }}
          PR_HEAD_SHA: ${{ env.PR_HEAD_SHA }}
          PR_NUMBER: ${{ needs.pr_workflow_payload.outputs.pr_number }}
        run: printf 'value=%s\n' "${AWS_S3_URL}/pull/${PR_NUMBER}/${PR_HEAD_SHA}/diff/diff-report.html" >> "$GITHUB_OUTPUT"

  diff_comment:
    needs:
      - deploy_diff
      - pr_workflow_payload
    runs-on: ubuntu-slim
    name: Diff comment
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Find diff URL comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find_url_comment
        with:
          issue-number: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- diff_report_url -->

      - name: Create or update comment with not empty diff
        if: ${{ needs.deploy_diff.outputs.has_diff == 'true' }}
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.find_url_comment.outputs.comment-id }}
          issue-number: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          body: |
            <!-- diff_report_url -->
            📊 Найдены изменения в собранных файлах: [Отчет](${{ needs.deploy_diff.outputs.url }})

            Commit ${{ env.PR_HEAD_SHA }}
          edit-mode: replace

      - name: Create or update comment with empty diff
        if: ${{ needs.deploy_diff.outputs.has_diff == 'false' }}
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.find_url_comment.outputs.comment-id }}
          issue-number: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          body: |
            <!-- diff_report_url -->
            ✅ Изменений в собранных файлах нет

            Commit ${{ env.PR_HEAD_SHA }}
          edit-mode: replace

  docs_comment:
    needs:
      - deploy_storybook
      - deploy_docs_website
      - deploy_package
      - pr_workflow_payload
    if: ${{ needs.deploy_storybook.outputs.url != '' || needs.deploy_docs_website.outputs.url != '' || needs.deploy_package.outputs.url != '' }}
    runs-on: ubuntu-slim
    name: Docs comment
    permissions:
      contents: read
      issues: write
      pull-requests: read
    steps:
      - name: Find docs URLs comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find_url_comment
        with:
          issue-number: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- docs_urls -->

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          comment-id: ${{ steps.find_url_comment.outputs.comment-id }}
          issue-number: ${{ needs.pr_workflow_payload.outputs.pr_number }}
          body: |
            <!-- docs_urls -->
            ## 👀 Docs deployed

            - ${{ (needs.deploy_docs_website.outputs.url != '' && '✅') || '❌' }} [Website](${{ needs.deploy_docs_website.outputs.url }})
            - ${{ (needs.deploy_storybook.outputs.url != '' && '✅') || '❌' }} [Playground](${{ needs.deploy_storybook.outputs.url }})

            ## 📦 Package ${{ (needs.deploy_package.outputs.url != '' && '✅') || '❌' }}

            ```sh
            yarn add @vkontakte/vkui@${{ needs.deploy_package.outputs.url }}
            ```

            Commit ${{ env.PR_HEAD_SHA }}
          edit-mode: replace
